version: '3.7'

services:
  db_support:
    container_name: db_support
    image: mysql:latest
    restart: 'unless-stopped'
    # command: --default-authentication-plugin=mysql_native_password
    volumes:
      - database_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: j4l4w4v3!@
    networks:
      - production

networks:
  production:
    name: production

volumes:
  database_data:
    name: database_data