version: '3.7'

services:
  db_support_dev:
    container_name: db_support_dev
    image: mysql:latest
    restart: 'always'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - development
    volumes:
      - database_data:/var/lib/mysql

  db_support_admin_dev:
    container_name: db_support_admin_dev
    image: phpmyadmin:latest
    restart: 'always'
    ports:
      - 3080:80
    depends_on:
      - db_support_dev
    environment:
      PMA_HOST: db_support_dev
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - development

networks:
  development:
    name: development

volumes:
  database_data:
    name: database_data